"""
Django settings for ChatTest project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import django

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]
DEBUG = True

ALLOWED_HOSTS = ['.railway.app','localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://chatapp-icebreak.up.railway.app']

RECAPTCHA_PUBLIC_KEY = '6LePHaAgAAAAAG45YAhTDKjoLUMcgPJ3Wjkrf0ta'
RECAPTCHA_PRIVATE_KEY = os.environ["RECAPTCHA_PRIVATE_KEY"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'Chat.apps.ChatConfig',
    'django_cleanup.apps.CleanupConfig',
    'captcha',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'ChatTest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ChatTest.wsgi.application'
ASGI_APPLICATION = 'ChatTest.routing.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ["PGDATABASE"],
        'USER': os.environ["PGUSER"],
        'PASSWORD': os.environ["PGPASSWORD"],
        'HOST': os.environ["PGHOST"],
        'PORT': os.environ["PGPORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'Chat.Account'


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIR = [os.path.join(BASE_DIR, 'static')]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL')],
        },
    },
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": [os.environ.get('REDIS_URL')],
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        }
    },
    'axes': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': '127.0.0.1:11211',
    }
}

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

SION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

#################################################################################

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = False  # Default: False - Store CSRF token in Session as opposed to in cookie
CSRF_COOKIE_HTTPONLY = False 

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

AXES_ENABLED = True 
AXES_FAILURE_LIMIT = 3 	
AXES_LOCK_OUT_AT_FAILURE = True
AXES_COOLOFF_TIME = 0.1         # in hours   - now set to 6 mins

AXES_LOCKOUT_CALLABLE = "Chat.views.lockout"

AXES_PROXY_ORDER = "left-most"
AXES_PROXY_COUNT = None
AXES_PROXY_TRUSTED_IPS = None
AXES_ONLY_WHITELIST = False
AXES_ONLY_ADMIN_SITE = False
AXES_ONLY_USER_FAILURES = False
AXES_ENABLE_ADMIN= True
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP= False
AXES_LOCK_OUT_BY_USER_OR_IP= False
AXES_USE_USER_AGENT= False 
AXES_CACHE='axes'
AXES_LOCKOUT_TEMPLATE=None
AXES_LOCKOUT_URL=None
AXES_VERBOSE=True
AXES_USERNAME_FORM_FIELD='username'
AXES_USERNAME_CALLABLE=None
AXES_WHITELIST_CALLABLE=None
AXES_PASSWORD_FORM_FIELD='password'
AXES_SENSITIVE_PARAMETERS=[]
AXES_NEVER_LOCKOUT_GET=False
AXES_NEVER_LOCKOUT_WHITELIST=True
AXES_IP_BLACKLIST=None
AXES_IP_WHITELIST=['']
AXES_DISABLE_ACCESS_LOG=True
AXES_ENABLE_ACCESS_FAILURE_LOG=True
AXES_ACCESS_FAILURE_LOG_PER_USER_LIMIT=5
AXES_RESET_ON_SUCCESS=True
AXES_ALLOWED_CORS_ORIGINS='*'
AXES_HTTP_RESPONSE_CODE=403
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT=True
AXES_CLIENT_STR_CALLABLE=None
AXES_COOLOFF_MESSAGE=None

AXES_META_PRECEDENCE_ORDER = [
    'HTTP_X_FORWARDED_FOR',
    'REMOTE_ADDR',
]

AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'

django.setup()
